name: Docker

on: [push, pull_request]

jobs:

  docker-ros:
    strategy:
      matrix:
        target: [dev, run]
        platform: [amd64]
    runs-on: self-hosted
    steps:
      - uses: ika-rwth-aachen/docker-ros@v1.3.1
        with:
          base-image: rwthika/ros2:humble
          command: ros2 launch carla_ros_bridge carla_ros_bridge.launch.py
          target: ${{ matrix.target }}
          platform: ${{ matrix.platform }}
          registry: docker.io
          registry-user: ${{ secrets.DOCKER_USERNAME }}
          registry-password: ${{ secrets.DOCKER_PASSWORD }}
          image-name: cgellerac/ros-bridge
          image-tag: ros2
          enable-singlearch-push: true
          enable-push-as-latest: true
