name: Docker

on: [push, pull_request]

jobs:

  docker-ros:
    strategy:
      matrix:
        target: [dev, run]
        platform: [amd64]
    runs-on: i2100038
    steps:
      - uses: robinraju/release-downloader@v1.8
        name: Download PythonAPI
        with:
          repository: carla-compose/carla
          latest: true
          fileName: PythonAPI.tar.gz
          extract: true
          out-file-path: docker/additional-files
      - name: Debug 1
        run: tree -L 3
      - uses: ika-rwth-aachen/docker-ros@v1.3.1
        name: Run docker-ros pipeline
        with:
          base-image: rwthika/ros2:humble
          command: ros2 launch carla_ros_bridge carla_ros_bridge.launch.py
          target: ${{ matrix.target }}
          platform: ${{ matrix.platform }}
          registry: docker.io
          registry-user: ${{ secrets.DOCKER_USERNAME }}
          registry-password: ${{ secrets.DOCKER_PASSWORD }}
          image-name: cgellerac/ros-bridge
          image-tag: ros2
          enable-singlearch-push: true
          enable-push-as-latest: true
      - name: Debug 2
        run: tree -L 3
